#!/bin/ksh -l
set -xa

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-nam}
export RUN=${RUN:-nam}

export PS4='$SECONDS + ' 
date

#
# obtain temp directory name
#
export pid=$$
export JJOBSnam=$HOMEnam/jobs
export WKDIRNAME=${job}.${pid}

# Setup directories and common environment variables

. ${JJOBSnam}/JNAM_ENVARS
export COMIN=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/gempak
export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/gempak/meta

export PS4='$SECONDS + '
date

export pid=$$
export pgmout="OUTPUT.${pid}"
export DATA=${DATAROOT:?}/${jobid:?}
mkdir $DATA
cd $DATA

#Only way to get this to work
#UTILROOT set by loading prod_util module
cp $UTILROOT/ush/* $DATA/.

####################################
# Determine Job Output Name on System
####################################

export pid=$$
export pgmout="OUTPUT.${pid}"

#############################################
#set the fcst hrs for the 00z and 12z cycles
#############################################
if [ $cyc -eq 00 -o $cyc -eq 12 ] ; then
   export fhbeg=00
   export fhend=84
   export fhinc=12
else
#set the fcst hrs for the 06z and 18z cycles
   export fhbeg=12
   export fhend=84
   export fhinc=12
fi

export cycle=t${cyc}z 
export DBN_ALERT_TYPE=NAM_METAFILE

####################################
# Specify Execution Areas
####################################
export HOMEnam=$NWROOT/nam.${nam_ver}
export HOMEgempak=$HOMEnam/gempak
export FIXgempak=$HOMEgempak/fix
export USHgempak=$HOMEgempak/ush

cp $FIXgempak/datatype.tbl datatype.tbl

# Run setpdy and initialize PDY variables
sh setpdy.sh
. PDY

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
env

msg="Begin job for $job"
postmsg "$jlogfile" "$msg"
########################################################
# Execute the script.
$HOMEnam/scripts/exnam_gempak_meta.sh.ecf
########################################################
msg="job has ended"
postmsg "$jlogfile" "$msg"
cat $pgmout

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-YES} = NO ] ; then rm -rf $DATA ; fi

date
