#!/bin/bash
set -xa

export HOMEnam=$NWROOT/nam.${nam_ver}
export JJOBSnam=$HOMEnam/jobs
export WKDIRNAME=${jobid:?}


# Setup directories and common environment variables

. ${JJOBSnam}/JNAM_ENVARS

module use -a /gpfs/dell1/nco/ops/nwprod/modulefiles/
module load gempak/7.3.1

# Get the domain id number. Note $domain is provided via the
# LSF job card or via Rocoto.
export numdomain=${numdomain:-`grep ${domain} ${PARMnam}/nam_nestdomains | awk '{print $2}'`}

########################################################
# Execute the script.
${HOMEnam}/scripts/exnam_postsnd_nest.sh.ecf
jerr=$?
########################################################

cat $pgmout
date
msg="JOB $job HAS COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-YES} = NO ] ; then rm -rf $DATA ; fi

exit $jerr
