#!/bin/bash
set -xa

export HOMEnam=$NWROOT/nam.${nam_ver}
export JJOBSnam=$HOMEnam/jobs
export WKDIRNAME=nam_${cyc}_${tmmark}_${envir}

# Setup directories and common environment variables

. ${JJOBSnam}/JNAM_ENVARS

  # Got these from the FV3GFS env.
  export MPI_LABELIO=YES
  export MP_STDOUTMODE="ORDERED"
  export KMP_STACKSIZE=2048M
  export KMP_AFFINITY=scatter

########################################################
# Execute the script.
${HOMEnam}/scripts/exnam_fcst_parentext.sh.ecf
jerr=$?
########################################################

cat $pgmout errfile
date
msg="JOB $job HAS COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

cd $DATA

exit $jerr
