#!/bin/bash
set -xa

export HOMEnam=$NWROOT/nam.${nam_ver}
export JJOBSnam=$HOMEnam/jobs
export WKDIRNAME=${jobid:?}

# Setup directories and common environment variables

. ${JJOBSnam}/JNAM_ENVARS
export COMAWP=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/gempak
mkdir -p $COMAWP

# Get the domain id number. Note $domain is provided via the
# LSF job card or via Rocoto.
export numdomain=${numdomain:-`grep ${domain} ${PARMnam}/nam_nestdomains | awk '{print $2}'`}

########################################################
# Execute the script.
${HOMEnam}/scripts/exnam_prdgen_nest.sh.ecf
jerr=$?
########################################################

echo "prdgen is done" > $FCSTDIR/prdgendone${fcsthrs}_${numdomain}.${tmmark}
cat $pgmout
date
msg="JOB $job HAS COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-YES} = NO ] ; then rm -rf $DATA ; fi

exit $jerr
