#!/bin/sh
set -xa

# these will be in ecflow script in ops
##. /usrx/local/prod/lmod/lmod/init/profile
##. /usrx/local/prod/modulefiles/.defaultmodules
##module load prod_util/1.1.1
##module load grib_util/1.0.6
##module load util_shared/1.1.0
##module load prod_envir/1.0.3

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export pgmout="OUTPUT.${pid}"
export DATA=${DATAROOT:?}/${jobid:?}
mkdir $DATA
cd $DATA

#################################
# Set up the NET and RUN
#################################
export NET=nam
export RUN=nam
export model=nam
export cycle=t${cyc}z 

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"

################################
# Set up the HOME directory
################################
export HOMEnam=$NWROOT/nam.${nam_ver}
export EXECnam=$HOMEnam/exec
export FIXnam=$HOMEnam/fix
export PARMnam=$HOMEnam/parm
export USHnam=$HOMEnam/ush

###################################
# Set up the UTILITIES ; UTILSHAREDROOT set in util_shared module load
###################################
export HOMEutil=$UTILSHAREDROOT
export EXECutil=$UTILSHAREDROOT/exec
export FIXutil=$FIXshared
export PARMutil=$HOMEnam/util/parm
export USHutil=$USHshared
export UTIL_USHnam=${UTIL_USHnam:-${HOMEnam}/util/ush}

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

########################################
# Set up the input/output directory
########################################
export COMIN=$COMROOT/nam/${envir}/${RUN}.${PDY}
export COMOUT=$COMROOT/nam/${envir}/${RUN}.${PDY}
export COMOUTwmo=$COMROOT/nam/${envir}/${RUN}.${PDY}/wmo
export pcom=$COMOUTwmo

mkdir -p $COMOUT $COMOUTwmo
env

########################################################
# Execute the script.
$HOMEnam/scripts/exnam_grib_awips.sh.ecf $fcsthrs
########################################################

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-YES} = NO ] ; then rm -rf $DATA ; fi

date
